# This is a sample build configuration for JavaScript.
# Check our guides at https://cloud.google.com/cloud-build/docs/deploying-builds/deploy-cloud-run
# Only use spaces to indent your .yaml configuration.
# -----
# You can specify a custom docker steps or other builder steps, look in docs
steps:
  # Pull Repo Code
  - name: 'gcr.io/cloud-builders/git'
    id: 'cloning-git-repo'
    args: ['clone', 'https://github.com/Danail-Irinkov/$_DEPLOYMENT', '--config', 'core.autocrlf=input']

  # Build the vsf containers
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build-vsf-vue'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_DEPLOYMENT', '-f', 'docker/vue-storefront/Dockerfile', '.']

  # Push the vsf containers to gcr.io repo
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push-vsf-vue'
    args: ['push', 'gcr.io/$PROJECT_ID/$_DEPLOYMENT']

  # Deploy to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'apply'
      - '-f'
      - 'kube'
      - '--location=${_K8S_ZONE}'
      - '--cluster=${_K8S_CLUSTER}'
    timeout: '100s'

#  # patch kubernetes deployment to trigger rolling update
#  - name: 'gcr.io/cloud-builders/kubectl'
#    args: [ 'patch', 'deployment', '${_DEPLOYMENT}', '-n', '${_NAMESPACE}', '-p',
#            '{"spec": {"template": {"metadata": {"annotations": {"build":"$BUILD_ID"}}, "spec": {"initContainers": [{"name": "app","image": "gcr.io/$PROJECT_ID/$_DEPLOYMENT:$BRANCH_NAME$TAG_NAME"}]}}}}' ]
#    env:
#      # required K8s cluster env variables
#      - 'CLOUDSDK_COMPUTE_ZONE=${_K8S_ZONE}'
#      - 'CLOUDSDK_CONTAINER_CLUSTER=${_K8S_CLUSTER}'
#
#  # check rolling deployment status
#  - name: 'gcr.io/cloud-builders/kubectl'
#    args: [ '-n', '${_NAMESPACE}', 'rollout', 'status', 'deploy/${_DEPLOYMENT}' ]
#    env:
#      # required K8s cluster env variables
#      - 'CLOUDSDK_COMPUTE_ZONE=${_K8S_ZONE}'
#      - 'CLOUDSDK_CONTAINER_CLUSTER=${_K8S_CLUSTER}'

  # slack deployment status
#  - name: 'gcr.io/cloud-builders/curl'
#    args: [ '-X', 'POST', '-H', 'Content-type: application/json', '--data',
#            '{"text":"${_DEPLOYMENT} deployment completed!"}', '${_WEBHOOK_URL}' ]



# arguments
substitutions:
  _K8S_ZONE:      europe-west3-c   # K8s zone
  _K8S_CLUSTER:   procc-kub2    # K8s cluster name
  _NAMESPACE:     default         # K8s namespace
  _DEPLOYMENT:    vue-storefront # K8s deployment name
  _WEBHOOK_URL:   slack_notification_webhook  # slack notifications
  _OAUTH_TOKEN:   composer_github_oauth_token # access to private code repos

# store artifact
#images: ['gcr.io/$PROJECT_ID/$_DEPLOYMENT:$BRANCH_NAME$TAG_NAME']
images: ['gcr.io/$PROJECT_ID/vue-storefront']

options:
  machineType: 'N1_HIGHCPU_8'
