apiVersion: v1
kind: Service
metadata:
  name: vue-storefront
  labels:
    app: vue-storefront
spec:
  type: NodePort
  selector:
    app: vue-storefront
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
