apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-storefront
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-storefront
  template:
    metadata:
      labels:
        app: vue-storefront
    spec:
      containers:
      - name: vue-storefront
        image: gcr.io/advance-anvil-247513/vsf-app-vue
        envFrom:
        - configMapRef:
            name: vue-storefront-config
        ports:
        - containerPort: 3000
        volumeMounts:
          - mountPath: /var/www/dist
            name: build-cache
          - mountPath: /var/www/config
            name: nfs-drive
            subPath: vsf_config
          - mountPath: /var/www/nfs
            name: nfs-drive
        resources:
          limits:
            memory: 2048Mi
          requests:
            memory: 1024Mi
      volumes:
        - name: build-cache
          emptyDir:
            medium: Memory
        - name: nfs-drive
          persistentVolumeClaim:
            claimName: nfs-drive-pvc
