apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-storefront
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  selector:
    matchLabels:
      app: vue-storefront
  template:
    metadata:
      labels:
        app: vue-storefront
    spec:
      containers:
      - name: vue-storefront
        image: gcr.io/advance-anvil-247513/vue-storefront
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 320
          periodSeconds: 30
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 500
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        envFrom:
        - configMapRef:
            name: vue-storefront-config
        ports:
        - containerPort: 3000
        volumeMounts:
          - mountPath: /var/www/dist
            name: build-cache
          - mountPath: /var/www/config
            name: nfs-drive
            subPath: vsf_config
          - mountPath: /var/www/src/themes/default-procc/resource/banners
            name: nfs-drive
            subPath: vsf_banners
          - mountPath: /var/www/src/themes/default-procc/resource/policies
            name: nfs-drive
            subPath: vsf_policies
#          - mountPath: /var/www/nfs
#            name: nfs-drive
        resources:
          limits:
            memory: 2048Mi
          requests:
            memory: 1024Mi
      volumes:
        - name: build-cache
          emptyDir:
            medium: Memory
        - name: nfs-drive
          persistentVolumeClaim:
            claimName: nfs-drive-pvc
