FROM divante/vue-storefront:latest

RUN apk add --no-cache --virtual .build-deps ca-certificates wget git python make g++ gcc libgcc libstdc++ py-pip openssl

RUN yarn global add webpack
RUN yarn global add forever
RUN yarn global add typescript

RUN apk update

ENV VS_ENV prod

WORKDIR /var/www

COPY package.json ./
COPY yarn.lock ./

RUN yarn install

COPY shims.d.ts ./
COPY tsconfig-build.json ./
COPY tsconfig.json ./
COPY lerna.json ./
COPY cypress.json ./
COPY .postcssrc ./
COPY .env ./
COPY .travis.yml ./
COPY .eslintrc.js ./
COPY .eslintignore ./
COPY ecosystem.json ./
COPY babel.config.js ./

COPY ./config ./config
COPY ./core ./core
COPY ./src ./src
COPY ./test ./test
COPY ./packages ./packages
COPY ./docker ./docker
COPY ./kubernetes ./kubernetes

EXPOSE 3000

RUN yarn build

RUN apk del .build-deps

#RUN ["yarn", "build"]

CMD ["yarn", "start"]
#CMD ["yarn", "start-build"]

#COPY docker/vue-storefront/vue-storefront.sh /usr/local/bin/
#
#CMD ["vue-storefront.sh"]
